### ISSUE TITLE
No connection to factordb database

### ISSUE THREAD

**Issue by shortjonescipher** [elliptic-shiho/primefac-fork#2]
The function factordb() in _factoralgo\\_factordb.py, needs to call f.connect() to connect to the factordb database at http://factordb.com/api.

**Comment by elliptic-shiho** [comment]
What is error message of that?

**Comment by shortjonescipher** [comment]
No error message, f.get_status() will not be in ['FF', 'CF'], so the function drops out returning None by default.

**Comment by shortjonescipher** [comment]
https://github.com/ryosan-470/factordb-pycli gives the required calling sequence under Library usage.

**Comment by elliptic-shiho** [comment]
Ahh... okay, I see, I'll fix it today (JST)
Thanks for notices!

**Comment by elliptic-shiho** [comment]
@shortjonescipher 
I fixed the bug at b94c52d . Thanks!
