### ISSUE TITLE
Can't install primefac-fork

### ISSUE THREAD

**Issue by Prokhozhijj** [elliptic-shiho/primefac-fork#7]
I have  MS Windows 10 64-bit, MS VS 2017, python 3.7

pip install git+git://github.com/elliptic-shiho/primefac-fork@master

Collecting git+git://github.com/elliptic-shiho/primefac-fork@master
  Cloning git://github.com/elliptic-shiho/primefac-fork (to revision master) to c:\users\prokh\appdata\local\temp\pip-req-build-_df08xib
  Running command git clone -q git://github.com/elliptic-shiho/primefac-fork 'C:\Users\prokh\AppData\Local\Temp\pip-req-build-_df08xib'
Requirement already satisfied: six in c:\python\python37\lib\site-packages (from primefac==1.1.1) (1.12.0)
Collecting gmpy (from primefac==1.1.1)
  Using cached https://files.pythonhosted.org/packages/26/37/2184c13cee81e1dbeaebbb13570195247e73ab2138a3db0c9d2c5347e372/gmpy-1.17.zip
Requirement already satisfied: factordb-pycli in c:\python\python37\lib\site-packages (from primefac==1.1.1) (1.2.0)
Requirement already satisfied: requests in c:\python\python37\lib\site-packages (from factordb-pycli->primefac==1.1.1) (2.22.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\python\python37\lib\site-packages (from requests->factordb-pycli->primefac==1.1.1) (1.25.3)
Requirement already satisfied: idna<2.9,>=2.5 in c:\python\python37\lib\site-packages (from requests->factordb-pycli->primefac==1.1.1) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python\python37\lib\site-packages (from requests->factordb-pycli->primefac==1.1.1) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\python\python37\lib\site-packages (from requests->factordb-pycli->primefac==1.1.1) (2019.6.16)
Installing collected packages: gmpy, primefac
  Running setup.py install for gmpy ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\prokh\\AppData\\Local\\Temp\\pip-install-f3nbtvi8\\gmpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\prokh\\AppData\\Local\\Temp\\pip-install-f3nbtvi8\\gmpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\prokh\AppData\Local\Temp\pip-record-80p_wjxi\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\prokh\AppData\Local\Temp\pip-install-f3nbtvi8\gmpy\
    Complete output (12 lines):
    running install
    running build
    running build_ext
    building 'gmpy' extension
    creating build
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\python\python37\include -Ic:\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tcsrc/gmpy.c /Fobuild\temp.win-amd64-3.7\Release\src/gmpy.obj
    gmpy.c
    c:\users\prokh\appdata\local\temp\pip-install-f3nbtvi8\gmpy\src\gmpy.h(30): fatal error C1083: Cannot open include file: 'gmp.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\prokh\\AppData\\Local\\Temp\\pip-install-f3nbtvi8\\gmpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\prokh\\AppData\\Local\\Temp\\pip-install-f3nbtvi8\\gmpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\prokh\AppData\Local\Temp\pip-record-80p_wjxi\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by Prokhozhijj** [comment]
After installing gmpy2-2.0.8-cp37-cp37m-win_amd64.whl taken from here [Unofficial Windows Binaries for Python Extension Packages](https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy) result is still the same as earlier.

**Comment by elliptic-shiho** [comment]
@Prokhozhijj  
> c:\users\prokh\appdata\local\temp\pip-install-f3nbtvi8\gmpy\src\gmpy.h(30): fatal error C1083: Cannot open include file: 'gmp.h': No such file or directory

gmpy/gmpy2 uses [gmp](https://gmplib.org/), you need to install that first.

This is not primefac-fork's issue. so I'll not support/guide of installation of these requirements packages.

**Comment by elliptic-shiho** [comment]
Ah, sorry, I add gmpy to requirements two years ago but I didn't updated README.md (updated just now).
This software uses gmpy, so you need to install that.

**Comment by Prokhozhijj** [comment]
Whether gmpy2 is not the same? If yes, I already installed it. Please see my second post here.

**Comment by elliptic-shiho** [comment]
Yes, gmpy is not gmpy2. primefac-fork can use both package but I specified gmpy in installation procedure because I using gmpy for several reasons (e.g. my environment compatibility).
I rewrited procedure to use gmpy2. could you retry to install?

**Comment by Prokhozhijj** [comment]
It works now. Thanks!
